version: "3.8"

services: 
  app:
    container_name: "withdrawdepsit"
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      APP_ENV: "development"
    restart: unless-stopped
