api:
  port: ":7000"
  timeout: 1000
auth:
  private_key: "privatekey"
  expire: "+30m"
database:
    mysql: 
      host: "192.168.1.10"
      port: "3306"
      dbname: "disbursement"
      user: "root"
      password: "root"
      sslmode: ""
context:
  timeout: 2